import QtQuick
import QtQuick.Layouts
// QtQuick.Controls is namespaced (QQC) so its `Button`/`Popup` etc. don't collide
// with the component-library Button.qml that shares this directory.
import QtQuick.Controls as QQC

// OptionsDialog — Part 1.4 (bullet 4). A faithful port of main:OpenOptionsPopup
// (Modules/Main.lua ~865): the ~28 application/build settings dialog. Built on
// PopupBase (Tier 0: dim overlay + centering + RETURN/ESCAPE + the title plate)
// and driven entirely by the engine bridge (luaEngine.getOptions /
// previewOption / commitOptions), which returns a flat descriptor list so the
// two option Sections are generated by a Repeater rather than hand-laid.
//
// Live-vs-commit split (mirrors the legacy Save/Cancel handlers exactly):
//   * commit==false (live-preview): node-power theme, hex colours, separators,
//     the checkboxes, default gem quality / char level / affix-quality slider —
//     applied to the engine IMMEDIATELY as the control changes (so e.g. the
//     node-power colours preview live elsewhere). Cancel/ESCAPE reverts each to
//     the snapshot captured on open.
//   * commit==true (Save-only): connectionProtocol, proxy scheme+URL, build save
//     path — held in a local draft and only pushed to the engine (+ persisted to
//     Settings.xml via SaveSettings) when Save is clicked.
//
// Entry point for the Bottom Bar stage: call optionsDialog.open() (the Dialog's
// own open() — onAboutToShow loads current engine state). See main.qml's hook.
PopupBase {
    id: root

    title: " Options "
    padding: 16

    // Raw descriptor list + the two working stores, (re)built on every open.
    property var _desc: []
    property var appOpts: []
    property var buildOpts: []
    property var _snapshot: ({})   // live-field pre-open values (Cancel target)
    property var _draft: ({})      // commit-field pending edits (Save target)

    // Both columns share a height so the two Sections line up.
    property real _colHeight: Math.max(appCol.implicitHeight, buildCol.implicitHeight) + 24

    // Load current engine state into the descriptor list + working stores.
    // Runs before the dialog is shown so the controls reflect live values.
    onAboutToShow: _load()
    // RETURN or the Save button -> accept(); ESCAPE or Cancel -> reject().
    onAccepted: _commit()
    onRejected: _revert()

    function _load() {
        var list = luaEngine.getOptions()
        if (!list) list = []
        var snap = ({})
        var draft = ({})
        var app = []
        var build = []
        for (var i = 0; i < list.length; i++) {
            var o = list[i]
            if (o.commit) draft[o.key] = o.value
            else snap[o.key] = o.value
            if (o.section === "Application options") app.push(o)
            else build.push(o)
        }
        root._desc = list
        root._snapshot = snap
        root._draft = draft
        root.appOpts = app
        root.buildOpts = build
    }

    function _applyChange(desc, v) {
        if (desc.commit) {
            var d = root._draft
            d[desc.key] = v
            root._draft = d
        } else {
            // Live-preview: mutate the engine immediately (configChanged fires).
            luaEngine.previewOption(desc.key, v)
        }
    }

    function _commit() {
        luaEngine.commitOptions(root._draft)
    }

    function _revert() {
        var snap = root._snapshot
        for (var k in snap)
            luaEngine.previewOption(k, snap[k])
    }

    // Per-key text-field width (build path is long, separators tiny, etc.).
    function _fieldWidth(desc) {
        if (desc.key === "buildPath") return 260
        if (desc.key === "proxyURL") return 190
        if (desc.type === "color") return 96
        if (desc.maxChars === 1) return 36
        if (desc.type === "int") return 70
        return 150
    }

    // ---- Inline dropdown (no DropDownControl in the Tier1/2 kit yet; built on
    // the Tier0 Chrome + Arrow + a QtQuick.Controls Popup for the list). ----
    component OptDropDown: Item {
        id: dd
        property var options: []
        property var currentVal
        signal activated(var val)

        implicitWidth: 150
        implicitHeight: 18

        readonly property int _idx: {
            var n = dd.options ? dd.options.length : 0
            for (var i = 0; i < n; i++)
                if (dd.options[i].val === dd.currentVal) return i
            return -1
        }

        Chrome { anchors.fill: parent; hovered: ddMa.containsMouse || ddMenu.visible }

        ColorText {
            anchors.left: parent.left
            anchors.leftMargin: 5
            anchors.right: caret.left
            anchors.rightMargin: 4
            anchors.verticalCenter: parent.verticalCenter
            elide: Text.ElideRight
            sourceText: dd._idx >= 0 ? dd.options[dd._idx].label : ""
            defaultColor: theme.text
            font.pixelSize: 13
        }
        Arrow {
            id: caret
            direction: "down"
            width: 9; height: 6
            anchors.right: parent.right
            anchors.rightMargin: 5
            anchors.verticalCenter: parent.verticalCenter
            glyphColor: theme.muted
        }
        MouseArea {
            id: ddMa
            anchors.fill: parent
            hoverEnabled: true
            onClicked: ddMenu.open()
        }
        QQC.Popup {
            id: ddMenu
            y: dd.height + 1
            width: dd.width
            implicitHeight: Math.min(260, ddCol.implicitHeight + 2)
            padding: 1
            background: Rectangle {
                color: theme.background
                border.color: theme.borderStrong
                border.width: 1
                radius: theme.radiusControl
            }
            contentItem: Column {
                id: ddCol
                width: ddMenu.width - 2
                Repeater {
                    model: dd.options
                    delegate: Rectangle {
                        required property var modelData
                        required property int index
                        width: ddCol.width
                        height: 20
                        color: itemMa.containsMouse ? theme.hover
                             : (index === dd._idx ? theme.titleBar : "transparent")
                        ColorText {
                            anchors.left: parent.left
                            anchors.leftMargin: 5
                            anchors.verticalCenter: parent.verticalCenter
                            sourceText: modelData.label
                            defaultColor: theme.text
                            font.pixelSize: 13
                        }
                        MouseArea {
                            id: itemMa
                            anchors.fill: parent
                            hoverEnabled: true
                            onClicked: {
                                dd.currentVal = modelData.val  // imperative override of the init binding
                                dd.activated(modelData.val)
                                ddMenu.close()
                            }
                        }
                    }
                }
            }
        }
    }

    // ---- Inline single-line text field (no EditControl in the kit yet; built on
    // Chrome + a plain QtQuick TextInput, which handles click-to-focus itself). ----
    component OptTextField: Item {
        id: tf
        property alias text: tfInput.text
        property int maxChars: 0
        signal edited(string t)

        implicitWidth: 150
        implicitHeight: 18

        HoverHandler { id: tfHover }
        Chrome { anchors.fill: parent; hovered: tfHover.hovered || tfInput.activeFocus }
        TextInput {
            id: tfInput
            anchors.fill: parent
            anchors.leftMargin: 5
            anchors.rightMargin: 5
            verticalAlignment: TextInput.AlignVCenter
            clip: true
            color: theme.text
            selectionColor: theme.accent
            selectedTextColor: theme.background
            font.family: theme.fontVar
            font.pixelSize: 13
            maximumLength: tf.maxChars > 0 ? tf.maxChars : 32767
            onTextEdited: tf.edited(text)
        }
    }

    // ---- One form row: right-aligned label + type-appropriate control. ----
    Component {
        id: rowDelegate
        RowLayout {
            id: rowRoot
            required property var modelData
            Layout.fillWidth: true
            spacing: 6

            ColorText {
                Layout.preferredWidth: 200
                Layout.alignment: Qt.AlignVCenter
                horizontalAlignment: Text.AlignRight
                wrapMode: Text.NoWrap
                elide: Text.ElideRight
                sourceText: rowRoot.modelData.label
                defaultColor: theme.text
                font.pixelSize: 13
            }

            Loader {
                id: ctlLoader
                Layout.alignment: Qt.AlignVCenter
                Layout.preferredHeight: 18
                Layout.preferredWidth: {
                    var t = rowRoot.modelData.type
                    if (t === "check") return 18
                    if (t === "dropdown") return 150
                    if (t === "slider") return 210
                    return root._fieldWidth(rowRoot.modelData)
                }
                sourceComponent: {
                    var t = rowRoot.modelData.type
                    if (t === "check") return checkComp
                    if (t === "dropdown") return dropComp
                    if (t === "slider") return sliderComp
                    return textComp
                }
            }

            Item { Layout.fillWidth: true } // spacer keeps controls left-aligned

            Component {
                id: checkComp
                CheckBox {
                    label: ""
                    state: rowRoot.modelData.value ? true : false
                    noTooltip: !(rowRoot.modelData.tooltip)
                    tooltipText: rowRoot.modelData.tooltip || ""
                    onToggled: root._applyChange(rowRoot.modelData, newState)
                }
            }
            Component {
                id: dropComp
                OptDropDown {
                    options: rowRoot.modelData.options
                    currentVal: rowRoot.modelData.value
                    onActivated: root._applyChange(rowRoot.modelData, val)
                }
            }
            Component {
                id: sliderComp
                RowLayout {
                    spacing: 6
                    Slider {
                        id: sl
                        Layout.preferredWidth: 160
                        Layout.preferredHeight: 18
                        property bool _ready: false
                        Component.onCompleted: { value = rowRoot.modelData.value; _ready = true }
                        onValueChanged: if (_ready) root._applyChange(rowRoot.modelData, value)
                    }
                    ColorText {
                        Layout.preferredWidth: 44
                        Layout.alignment: Qt.AlignVCenter
                        sourceText: Math.round(sl.value * 100) + "%"
                        defaultColor: theme.text
                        font.pixelSize: 13
                    }
                }
            }
            Component {
                id: textComp
                OptTextField {
                    text: rowRoot.modelData.value !== undefined ? String(rowRoot.modelData.value) : ""
                    maxChars: rowRoot.modelData.maxChars || 0
                    onEdited: root._applyChange(rowRoot.modelData, t)
                }
            }
        }
    }

    // ---- Dialog body: two option columns + the Save/Cancel button row. ----
    ColumnLayout {
        spacing: 10

        RowLayout {
            id: columns
            Layout.alignment: Qt.AlignTop
            spacing: 16

            Section {
                label: "Application options"
                Layout.preferredWidth: 470
                Layout.preferredHeight: root._colHeight
                Layout.alignment: Qt.AlignTop
                ColumnLayout {
                    id: appCol
                    anchors.fill: parent
                    anchors.margins: 8
                    anchors.topMargin: 14
                    spacing: 3
                    Repeater { model: root.appOpts; delegate: rowDelegate }
                    Item { Layout.fillHeight: true }
                }
            }

            Section {
                label: "Build-related options"
                Layout.preferredWidth: 470
                Layout.preferredHeight: root._colHeight
                Layout.alignment: Qt.AlignTop
                ColumnLayout {
                    id: buildCol
                    anchors.fill: parent
                    anchors.margins: 8
                    anchors.topMargin: 14
                    spacing: 3
                    Repeater { model: root.buildOpts; delegate: rowDelegate }
                    Item { Layout.fillHeight: true }
                }
            }
        }

        RowLayout {
            Layout.alignment: Qt.AlignHCenter
            spacing: 12
            Button {
                label: "Save"
                implicitWidth: 90
                onClicked: root.accept()
            }
            Button {
                label: "Cancel"
                implicitWidth: 90
                onClicked: root.reject()
            }
        }
    }
}
